kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triggers-minimal
  namespace: cdevents
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdevent-listener
  namespace: cdevents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cdevent-listener-triggers-minimal
  namespace: cdevents
subjects:
- kind: ServiceAccount
  name: cdevent-listener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triggers-minimal
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-map-admin
  namespace: cdevents
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-config-map-admin
  namespace: cdevents
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdevent-listener-triggers
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "clustertriggerbindings", "clusterinterceptors"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cdevent-listener-triggers-cdevents
subjects:
- kind: ServiceAccount
  name: cdevent-listener
  namespace: cdevents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdevent-listener-triggers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: cdevents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer
rules:
  - apiGroups: [""]
    resources: [services]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [pods]
    verbs: ["get", "list", "watch"]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: ["*"]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-deployer-production
  namespace: production
subjects:
  - kind: ServiceAccount
    name: runner
    namespace: cdevents
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer